name: Infrastructure deployment

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths: ["./time-tracking-app/infra/*"]

  pull_request:
    branches: [main]
    paths: ["./time-tracking-app/infra/*"]

jobs:
  plan:
    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.backend_iam_role }}
          aws-region: ${{ vars.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: TF init
        shell: bash
        run: |
          set -eux
          terraform init -upgrade -reconfigure \
            -backend-config='skip_metadata_api_check=true' \
            -backend-config='skip_region_validation=true' \
            -backend-config='skip_credentials_validation=true' \
            -backend-config='region=${{ vars.aws_region }}' \
            -backend-config='bucket=${{ vars.backend_s3_bucket }}' \
            -backend-config='key=timethief-app/terraform-infra.tfstate' \
            -backend-config='dynamodb_table=${{ vars.infra_dynamodb_table }}' \
        working-directory: ./time-tracking-app/infra

  deploy:
    name: TF deploy
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.backend_iam_role }}
          aws-region: ${{ vars.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: TF init
        shell: bash
        run: |
          set -eux
          terraform init -upgrade -reconfigure \
            -backend-config='skip_metadata_api_check=true' \
            -backend-config='skip_region_validation=true' \
            -backend-config='skip_credentials_validation=true' \
            -backend-config='region=${{ vars.aws_region }}' \
            -backend-config='bucket=${{ vars.backend_s3_bucket }}' \
            -backend-config='key=timethief-app/terraform-infra.tfstate' \
            -backend-config='dynamodb_table=${{ vars.infra_dynamodb_table }}' \
        #-backend-config='role_arn=arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.backend_iam_role }}'
        working-directory: ./time-tracking-app/infra

      - name: TF apply
        shell: bash
        run: |
          set -eux
          terraform apply \
            -var 'aws_account_id=${{ vars.aws_account_id }}' \
            -auto-approve
        #-var 'iam_role=arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.hub_iam_role }}' \
        working-directory: ./time-tracking-app/infra