name: destroy infrastructure

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: vars.runner_os

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.backend_iam_role }}
          aws-region: ${{ vars.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: TF init
        shell: bash
        run: |
          set -eux
          terraform init -upgrade -reconfigure \
            -backend-config='skip_metadata_api_check=true' \
            -backend-config='skip_region_validation=true' \
            -backend-config='skip_credentials_validation=true' \
            -backend-config='region=${{ vars.aws_region }}' \
            -backend-config='bucket=${{ vars.backend_s3_bucket }}' \
            -backend-config='key=timethief-app/terraform-infra.tfstate' \
            -backend-config='dynamodb_table=${{ vars.infra_dynamodb_table }}' \
        working-directory: vars.infra_path

      - name: TF destroy
        shell: bash
        run: |
          set -eux
          terraform destroy \
            -auto-approve
        working-directory: vars.infra_path